-- -----------------------------------------------------
-- Criando Views
-- -----------------------------------------------------

CREATE VIEW IF NOT EXISTS 

CREATE VIEW IF NOT EXISTS 

CREATE VIEW IF NOT EXISTS 

CREATE VIEW IF NOT EXISTS 

CREATE VIEW IF NOT EXISTS 

CREATE VIEW IF NOT EXISTS 

CREATE VIEW IF NOT EXISTS 

CREATE VIEW IF NOT EXISTS 

CREATE VIEW IF NOT EXISTS 

CREATE VIEW IF NOT EXISTS 

